### PR TITLE
Fix #172: Call the correct method name for autorun INITIAL states

### LINKED ISSUE #172: Autorun INITIAL state throws an error
# Issue Template

### Description

When creating an `autorun="yes"` INITIAL state, instantiating that workflow throws a "can't call method `name` on Workflow::State instance" type of error message. The correct method name would have been `state`.

# Bugs and Issues

### Specify what version was used

1.56

### Expected behaviour

The workflow is advanced to the next state.

### Actual and observed behaviour

An error was thrown.

### Steps to reproduce the behaviour

A test, script or one-liner is preferred, but anything that can help is good

### PR DESCRIPTION
**Pull request by ehuelsmann**
# Description

Fixes/addresses (If applicable) #171 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project, please see the [contribution guidelines](https://github.com/jonasbn/perl-workflow/blob/master/CONTRIBUTING.md).
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by jonasbn** [comment]
I do not think this is an issue as such, but we might want to stick to 0.24 or make sure if the toolchain works, there is some suggestion that the issue originates from other dependencies and is fixed in XS::Parse::Keyword 0.10

REF: RT: [136860](https://rt.cpan.org/Public/Bug/Display.html?id=136860)

**Comment by ehuelsmann** [comment]
> I do not think this is an issue as such, but we might want to stick to 0.24 or make sure if the toolchain works, there is some suggestion that the issue originates from other dependencies and is fixed in XS::Parse::Keyword 0.10
> 
> REF: RT: [136860](https://rt.cpan.org/Public/Bug/Display.html?id=136860)

The issue is known with the author and I'm working with him on a fixed version of XS::Parse::Keyword::Builder, which is the cause of the installation problem (contacted him last night about it). The likely solution is to change some C conditional in the XS::* sources.

**Comment by jonasbn** [comment]
I think we are good

**Comment by ehuelsmann** [comment]
Thanks for merging! There's some discussion left before we can go to 2.0, but i would really like to have this fix. Do you think we should do 1.57?

**Comment by jonasbn** [comment]
Moved to milestone 1.57 from 2.00

**Pull request merged**
